import React from "react";

export default function Disclaimer() {
  return (
    <div className="flex flex-col gap-2 text-muted-foreground italic">
      <div className="text-md  p-4">
        AI-generated outputs may contain errors, omissions, or outdated
        information. Review all suggestions carefully before applying them to
        your resume.
      </div>

      <ol className="list-none text-[0.65rem] pl-4 gap-2">
        <li className="mb-2">
          ¹ <span className="font-bold">Resume Review </span> The resume review
          scores and feedback are generated by an AI model and are intended for
          general guidance only. Ratings such as ATS compatibility, summary
          strength, and skills evaluation are based on automated analysis and
          may not reflect the criteria used by actual recruiters, hiring
          managers, or applicant tracking systems. Results should not be
          interpreted as guarantees of interview selection or hiring outcomes.
        </li>

        <li className="mb-2">
          ² <span className="font-bold">Job Match </span> The overall job match
          score is generated using AI-based comparison between the resume
          content and a generalised interpretation of role requirements. The
          score is indicative only and may not reflect the evaluation methods
          used by employers. A high match score does not guarantee suitability
          for a specific vacancy, interview selection, or hiring decision.
        </li>

        <li className="mb-2">
          ³ <span className="font-bold">Job Recommendations </span> The
          suggested job titles, roles, responsibilities, skills, and career
          paths are AI-generated recommendations based on resume content and
          common industry patterns. These suggestions are not exhaustive and may
          not reflect all suitable opportunities. Users should independently
          assess role requirements and career fit before applying.
        </li>

        <li className="mb-2">
          ⁴ <span className="font-bold">Suggested Listings </span> Job listings
          and search queries are provided for convenience only and may include
          examples derived from publicly available information. Listings may
          change, expire, or be removed by the hosting platforms. The presence
          of a listing does not imply endorsement, availability, or suitability.
          Users should verify details directly on the respective job platform
          before applying.
        </li>
      </ol>
    </div>
  );
}
